name: Build and Deploy Python Flask App and Frontend to Azure App Service

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 前端构建步骤
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 根据你前端使用的 Node.js 版本设置

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install  # 安装前端依赖

    - name: Build frontend
      run: |
        cd frontend
        npm run build  # 构建前端应用

    - name: Deploy frontend to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        app-name: <your-frontend-app-service-name>  # 你的 Azure Static Web Apps 名称
        api-location: 'backend'  # 后端 API 代码所在路径
        app-location: 'frontend'  # 前端代码所在路径
        output-location: 'frontend/build'  # 前端构建的输出目录

    # 后端构建步骤
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install backend dependencies
      run: |
        pip install -r backend/requirements.txt  # 安装后端依赖

    - name: Deploy backend to Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: <your-backend-app-service-name>  # 你的 Azure App Service 名称
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure 发布配置文件
        package: backend/  # 后端代码所在目录
